# Generated by Django 4.2.5 on 2023-10-06 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Doctors', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('title', models.CharField(default='Dr.', max_length=200, verbose_name='Title')),
                ('phone_no', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('d_o_b', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('biography', models.CharField(blank=True, max_length=1000, verbose_name='Biography')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='County')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Town')),
                ('pricing', models.FloatField(default=0.0, verbose_name='Amount')),
                ('services', models.CharField(blank=True, max_length=1000, verbose_name='Services')),
                ('specialization', models.CharField(blank=True, max_length=1000, verbose_name='Specialization')),
                ('clinic', models.CharField(blank=True, max_length=100, verbose_name='Clinic')),
                ('clinic_address', models.CharField(blank=True, max_length=100, verbose_name='Clinic Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Year')),
                ('registration', models.CharField(max_length=50, verbose_name='Registration')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Patient/Profile/', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('d_o_b', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone_no', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('blood_group', models.CharField(max_length=5, verbose_name='Blood Group')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('county', models.CharField(max_length=50, verbose_name='County')),
                ('town', models.CharField(max_length=50, verbose_name='Town')),
                ('street_lane', models.CharField(max_length=50, verbose_name='Street/Lane')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose')),
                ('category', models.CharField(max_length=50, verbose_name='Type')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Appointment Date')),
                ('booking_date', models.DateTimeField(verbose_name='Booking Date')),
                ('follow_up_date', models.DateTimeField(null=True, verbose_name='Follow Up')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Administrator', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('d_o_b', models.DateField(verbose_name='Date of Birth')),
                ('phone_no', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('address_line', models.CharField(blank=True, max_length=200, verbose_name='Address Line')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='County')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Town')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
