# Generated by Django 4.2.5 on 2023-10-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dctor_register_patient_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dctor_register',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='patient_register',
            old_name='first_name',
            new_name='fname',
        ),
    ]
