# Generated by Django 4.2.5 on 2023-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_first_name_dctor_register_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(default='dummy.png', max_length=500, upload_to='Image/Admin', verbose_name='Profile Image'),
        ),
    ]
