# Generated by Django 4.2.5 on 2023-10-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_admin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=40)),
                ('otp', models.IntegerField()),
                ('token', models.CharField(max_length=65)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Review Date')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('recommend', models.BooleanField(default=False, verbose_name='Recommend')),
                ('text', models.CharField(blank=True, max_length=150, verbose_name='Review Title')),
                ('appointment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
            ],
        ),
    ]
